name: CI

on: [push]

jobs:
  sast_scan:
    name: Run Bandit Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Bandit
      run: pip install bandit

    - name: Run Bandit Scan
      run: bandit -ll -ii -r . -f json -o bandit-report.json

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: bandit-findings.json
        path: bandit-report.json

  image_scan:
    name: Build and Run Image Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker-practice/actions-setup-docker@v1
      with:
        docker_version: '20.10.7'

    - name: Build Docker Image
      run: docker build -f Dockerfile -t mytestapp:latest .

    - name: Docker Scout Scan
      uses: docker/scout-action@v1.15.1
      with:
        dockerhub-user: ${{ secrets.DOCKERHUB_USERNAME }}
        dockerhub-password: ${{ secrets.DOCKERHUB_PASSWORD }}
        command: quickview,cves
        only-severities: critical,high
        sarif-file: scout-report.sarif
        exit-code: true

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: docker-scout-findings
        path: scout-report.sarif

  dast_scan:
    name: DAST Scan with OWASP ZAP
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy PyGoat
      run: |
        docker pull pygoat/pygoat:latest
        docker run --rm -d -p 8000:8000 pygoat/pygoat:latest

    - name: Run OWASP ZAP DAST Scan
      run: |
        docker pull zaproxy/zap-bare
        docker run --rm -v $(pwd):/zap/wrk/:rw zaproxy/zap-bare zap-baseline.py \
            -t http://localhost:8000 \
            -r zap-report.html

    - name: Upload DAST Report
      uses: actions/upload-artifact@v3
      with:
        name: dast-scan-report
        path: zap-report.html
